version: "2"

services:
  # Основной сервис
  app:
    build: .
    container_name: metric-service
    restart: on-failure:5
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
    env_file:
      - .env
    environment:
      TZ: Europe/Moscow